In [1]:
# Import the libraries
import numpy as np

In [2]:
# Create a coefficient matrix
A = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
A

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [3]:
# Create a known term vector
b = np.array([10, 2, 50, 3])
b = b.reshape(4, 1)
b

array([[10],
       [ 2],
       [50],
       [ 3]])

In [4]:
# Create the complete matrix
Ab = np.concatenate((A, b), axis=1)
Ab

array([[ 87,  96,  70,  10],
       [100,  87,  90,   2],
       [ 94,  77,  90,  50],
       [100,  81,  82,   3]])

In [5]:
# Compute the ranks
rA = np.linalg.matrix_rank(A)
rA

3

In [6]:
rAb = np.linalg.matrix_rank(Ab)
rAb

4

In [7]:
# A new coefficient matrix
A = np.array([[1, 0, 1], [0, 1, 1], [1, 2, 2]])
A

array([[1, 0, 1],
       [0, 1, 1],
       [1, 2, 2]])

In [8]:
# A new known term vector
b = np.array([4, 5, 1])
b = b.reshape(3, 1)
b

array([[4],
       [5],
       [1]])

In [9]:
# A new complete matrix
Ab = np.concatenate((A, b), axis=1)
Ab

array([[1, 0, 1, 4],
       [0, 1, 1, 5],
       [1, 2, 2, 1]])

In [10]:
# Compute the new ranks
rA = np.linalg.matrix_rank(A)
rA

3

In [11]:
rAb = np.linalg.matrix_rank(Ab)
rAb

3

In [12]:
# Solve the system
Ainv = np.linalg.inv(A)
x = Ainv @ b
x

array([[-9.],
       [-8.],
       [13.]])