In [1]:
# Import the libraries
import numpy as np
import itertools

In [2]:
A = np.array([[1, 2, 3], [1, 2, 5], [1, 2, 1]])
A

array([[1, 2, 3],
       [1, 2, 5],
       [1, 2, 1]])

In [3]:
# Find a subset of r linearly independet columns of A (if it exists)
def non_redundant(A, r):
    rows, cols = A.shape
    indices = range(cols) #[0, 1, ..., cols-1]
    
    # Iterate among all subsets of r columns
    for subcols in itertools.combinations(indices, r):
        # Extract a submatrix with r columns
        subA = A[:, subcols]
        # Compute the rank of the submatrix with r columns
        r_subA = np.linalg.matrix_rank(subA)
        if r_subA == r:
            return subA
    

In [4]:
non_redundant(A, 1)

array([[1],
       [1],
       [1]])

In [5]:
non_redundant(A, 2)

array([[1, 3],
       [1, 5],
       [1, 1]])

In [6]:
# The function return nothing since there are no 3 linerly independent columns
non_redundant(A, 3)