In [1]:
# Import libraries
import numpy as np

In [2]:
# Build the market
B1 = np.array([10, 10, 10])
S1_1 = np.array([20, 30, 5])
S1_2 = np.array([5, 5, 10])

In [3]:
M1 = np.array([B1, S1_1, S1_2]).T

In [4]:
M1

array([[10, 20,  5],
       [10, 30,  5],
       [10,  5, 10]])

In [5]:
# Verify that the market is complete
r = np.linalg.matrix_rank(M1)
rows, cols = M1.shape

In [6]:
if r == rows:
    print('The market is complete')
else:
    print('The market is incomplete')

if r == rows and r == cols:
    print('No redundant assets')

The market is complete
No redundant assets


In [7]:
# Payoff of the call
K = 20
C1 = np.maximum(S1_1 - K, 0)
C1 = C1.reshape(3, 1)
C1

array([[ 0],
       [10],
       [ 0]])

In [8]:
# Replicating portfolio
M1inv = np.linalg.inv(M1)
theta = M1inv @ C1
theta

array([[-3.5],
       [ 1. ],
       [ 3. ]])

In [9]:
# Best hedge through OLS
reg = np.linalg.lstsq(M1, C1, rcond=-1)
theta_best = reg[0]
theta_best

array([[-3.5],
       [ 1. ],
       [ 3. ]])

In [10]:
# MAE
MAE = (np.abs(theta - theta_best)).mean()
MAE

5.181040781584064e-16

In [11]:
# Round MAE at two decimals
np.round(MAE, 2)

0.0